version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

  web:
    container_name: web
    image: php-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq